/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as NewArrivalsRouteImport } from './routes/new-arrivals'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as BikeModelsIndexRouteImport } from './routes/bike-models.index'
import { Route as BikeModelsSlugRouteImport } from './routes/bike-models.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const NewArrivalsRoute = NewArrivalsRouteImport.update({
  id: '/new-arrivals',
  path: '/new-arrivals',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const BikeModelsIndexRoute = BikeModelsIndexRouteImport.update({
  id: '/bike-models/',
  path: '/bike-models/',
  getParentRoute: () => rootRouteImport,
} as any)
const BikeModelsSlugRoute = BikeModelsSlugRouteImport.update({
  id: '/bike-models/$slug',
  path: '/bike-models/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/shop': typeof ShopRoute
  '/bike-models/$slug': typeof BikeModelsSlugRoute
  '/bike-models/': typeof BikeModelsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/shop': typeof ShopRoute
  '/bike-models/$slug': typeof BikeModelsSlugRoute
  '/bike-models': typeof BikeModelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/shop': typeof ShopRoute
  '/bike-models/$slug': typeof BikeModelsSlugRoute
  '/bike-models/': typeof BikeModelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/new-arrivals'
    | '/shop'
    | '/bike-models/$slug'
    | '/bike-models/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/new-arrivals'
    | '/shop'
    | '/bike-models/$slug'
    | '/bike-models'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/new-arrivals'
    | '/shop'
    | '/bike-models/$slug'
    | '/bike-models/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  NewArrivalsRoute: typeof NewArrivalsRoute
  ShopRoute: typeof ShopRoute
  BikeModelsSlugRoute: typeof BikeModelsSlugRoute
  BikeModelsIndexRoute: typeof BikeModelsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-arrivals': {
      id: '/new-arrivals'
      path: '/new-arrivals'
      fullPath: '/new-arrivals'
      preLoaderRoute: typeof NewArrivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bike-models/': {
      id: '/bike-models/'
      path: '/bike-models'
      fullPath: '/bike-models/'
      preLoaderRoute: typeof BikeModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bike-models/$slug': {
      id: '/bike-models/$slug'
      path: '/bike-models/$slug'
      fullPath: '/bike-models/$slug'
      preLoaderRoute: typeof BikeModelsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  NewArrivalsRoute: NewArrivalsRoute,
  ShopRoute: ShopRoute,
  BikeModelsSlugRoute: BikeModelsSlugRoute,
  BikeModelsIndexRoute: BikeModelsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
